# Add to composer.json
# {
#     "name": "My cool Reyesoft project"
#     "sasslintConfig": "node_modules/js/rules/.sass.lint.yml"
# }

options:
  config-file: node_modules/js/rules/.sass.lint.yml
files:
  include: 'src/**/*.s+(a|c)ss'
rules:
  # Project particular extends
